export const tests = [
  {
    id: 1,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Solve for x: 2x + 5 = 11",
    options: ["x = 3", "x = 6", "x = 2", "x = 7"],
    correctIndex: 1,
  },
  {
    id: 2,
    theme: "Geometric Area",
    difficulty: "medium",
    question: "What is the area of a triangle with base 8 and height 4?",
    options: [
      "12 square units",
      "16 square units",
      "20 square units",
      "24 square units",
    ],
    correctIndex: 2,
  },
  {
    id: 3,
    theme: "Basic Multiplication",
    difficulty: "easy",
    question: "What is 3 multiplied by 5?",
    options: ["8", "12", "15", "5"],
    correctIndex: 2,
  },
  {
    id: 4,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Simplify the expression: 3(x + 4) - 2(2x - 1)",
    options: ["-3x + 10", "5x - 10", "x - 8", "7x - 2"],
    correctIndex: 0,
  },
  {
    id: 5,
    theme: "Perimeter and Area",
    difficulty: "medium",
    question: "What is the perimeter of a rectangle with length 7 and width 4?",
    options: ["22 units", "28 units", "30 units", "15 units"],
    correctIndex: 1,
  },
  {
    id: 6,
    theme: "Basic Arithmetic",
    difficulty: "easy",
    question: "What is 16 divided by 4?",
    options: ["4", "8", "12", "16"],
    correctIndex: 0,
  },
  {
    id: 7,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Solve for y: 2y - 7 = 11",
    options: ["y = 9", "y = 7", "y = 6", "y = 12"],
    correctIndex: 3,
  },
  {
    id: 8,
    theme: "Geometric Circumference",
    difficulty: "medium",
    question: "What is the circumference of a circle with a radius of 5?",
    options: ["10π", "15π", "20π", "25π"],
    correctIndex: 0,
  },
  {
    id: 9,
    theme: "Basic Addition",
    difficulty: "easy",
    question: "What is 7 plus 3?",
    options: ["8", "10", "12", "6"],
    correctIndex: 1,
  },
  {
    id: 10,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Simplify the expression: 5(2x + 3) - 2(3x - 1)",
    options: ["3x + 13", "7x + 11", "4x + 7", "10x + 5"],
    correctIndex: 2,
  },
  {
    id: 11,
    theme: "Geometric Area",
    difficulty: "medium",
    question: "What is the area of a circle with a radius of 6?",
    options: [
      "12π square units",
      "18π square units",
      "24π square units",
      "36π square units",
    ],
    correctIndex: 3,
  },
  {
    id: 12,
    theme: "Basic Subtraction",
    difficulty: "easy",
    question: "What is 9 minus 2?",
    options: ["6", "7", "5", "11"],
    correctIndex: 1,
  },
  {
    id: 13,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Solve for x: 4x - 9 = 15",
    options: ["x = 6", "x = 7", "x = 8", "x = 9"],
    correctIndex: 2,
  },
  {
    id: 14,
    theme: "Geometric Volume",
    difficulty: "medium",
    question: "What is the volume of a cube with side length 4?",
    options: [
      "16 cubic units",
      "32 cubic units",
      "64 cubic units",
      "48 cubic units",
    ],
    correctIndex: 0,
  },
  {
    id: 15,
    theme: "Basic Multiplication",
    difficulty: "easy",
    question: "What is 6 multiplied by 7?",
    options: ["30", "36", "42", "48"],
    correctIndex: 2,
  },
  {
    id: 16,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Simplify the expression: 2(3x + 5) + 4(2x - 1)",
    options: ["10x + 14", "12x + 10", "7x + 8", "8x + 14"],
    correctIndex: 1,
  },
  {
    id: 17,
    theme: "Geometric Perimeter",
    difficulty: "medium",
    question: "What is the perimeter of a square with side length 9?",
    options: ["27 units", "36 units", "45 units", "81 units"],
    correctIndex: 1,
  },
  {
    id: 18,
    theme: "Basic Division",
    difficulty: "easy",
    question: "What is 25 divided by 5?",
    options: ["4", "5", "6", "7"],
    correctIndex: 1,
  },
  {
    id: 19,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Solve for y: 3y + 8 = 20",
    options: ["y = 4", "y = 6", "y = 5", "y = 7"],
    correctIndex: 2,
  },
  {
    id: 20,
    theme: "Geometric Area",
    difficulty: "medium",
    question: "What is the area of a square with side length 12?",
    options: [
      "36 square units",
      "48 square units",
      "64 square units",
      "144 square units",
    ],
    correctIndex: 3,
  },
  {
    id: 21,
    theme: "Basic Addition",
    difficulty: "easy",
    question: "What is 8 plus 9?",
    options: ["15", "16", "17", "18"],
    correctIndex: 2,
  },
  {
    id: 22,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Simplify the expression: 4(2x + 7) - 3(3x - 2)",
    options: ["5x + 29", "7x + 17", "8x + 22", "6x + 19"],
    correctIndex: 1,
  },
  {
    id: 23,
    theme: "Geometric Area",
    difficulty: "medium",
    question: "What is the volume of a sphere with a radius of 3?",
    options: [
      "12π cubic units",
      "18π cubic units",
      "24π cubic units",
      "36π cubic units",
    ],
    correctIndex: 0,
  },
  {
    id: 24,
    theme: "Basic Subtraction",
    difficulty: "easy",
    question: "What is 12 minus 7?",
    options: ["3", "4", "5", "6"],
    correctIndex: 3,
  },
  {
    id: 25,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Solve for x: 5x - 3 = 12",
    options: ["x = 3", "x = 4", "x = 5", "x = 6"],
    correctIndex: 2,
  },
  {
    id: 26,
    theme: "Geometric Circumference",
    difficulty: "medium",
    question: "What is the circumference of a circle with a radius of 7?",
    options: ["14π", "21π", "28π", "35π"],
    correctIndex: 1,
  },
  {
    id: 27,
    theme: "Basic Multiplication",
    difficulty: "easy",
    question: "What is 10 multiplied by 6?",
    options: ["36", "60", "50", "70"],
    correctIndex: 1,
  },
  {
    id: 28,
    theme: "Linear Equations",
    difficulty: "medium",
    question: "Simplify the expression: 3(4x + 6) - 2(2x - 3)",
    options: ["8x + 24", "14x + 18", "12x + 12", "10x + 30"],
    correctIndex: 0,
  },
  {
    id: 29,
    theme: "Geometric Area",
    difficulty: "medium",
    question: "What is the area of a rectangle with length 10 and width 6?",
    options: [
      "60 square units",
      "40 square units",
      "30 square units",
      "20 square units",
    ],
    correctIndex: 0,
  },
  {
    id: 30,
    theme: "Basic Division",
    difficulty: "easy",
    question: "What is 15 divided by 3?",
    options: ["4", "5", "6", "7"],
    correctIndex: 1,
  },
  {
    id: 31,
    theme: "Advanced Algebra",
    difficulty: "hard",
    question: "Solve for x: 3x^2 - 12x + 9 = 0",
    options: ["x = 3", "x = 2", "x = 4", "x = 5"],
    correctIndex: 0,
  },
  {
    id: 32,
    theme: "Trigonometry",
    difficulty: "hard",
    question: "Find the exact value of sin(60 degrees).",
    options: ["0.5", "0.866", "0.707", "1.0"],
    correctIndex: 1,
  },
  {
    id: 33,
    theme: "Advanced Geometry",
    difficulty: "hard",
    question: "What is the surface area of a sphere with a radius of 10?",
    options: [
      "100π square units",
      "400π square units",
      "200π square units",
      "300π square units",
    ],
    correctIndex: 1,
  },
  {
    id: 34,
    theme: "Calculus",
    difficulty: "hard",
    question: "Find the derivative of f(x) = 3x^4 - 8x^3 + 2x^2 - 5x + 1.",
    options: [
      "12x^3 - 24x^2 + 4x - 5",
      "9x^3 - 24x^2 + 4x - 5",
      "12x^3 - 21x^2 + 2x - 5",
      "9x^3 - 21x^2 + 2x - 5",
    ],
    correctIndex: 0,
  },
  {
    id: 35,
    theme: "Probability",
    difficulty: "hard",
    question:
      "What is the probability of rolling two six-sided dice and getting a sum of 7?",
    options: ["1/6", "5/36", "1/12", "1/18"],
    correctIndex: 1,
  },
  {
    id: 36,
    theme: "Advanced Trigonometry",
    difficulty: "hard",
    question: "Find the exact value of tan(45 degrees).",
    options: ["0.5", "1.0", "0.707", "0.866"],
    correctIndex: 1,
  },
  {
    id: 37,
    theme: "Advanced Calculus",
    difficulty: "hard",
    question: "Evaluate the integral ∫(2x^3 - 3x^2 + 4x - 1) dx.",
    options: [
      "(x^4 - x^3 + 2x^2 - x) + C",
      "(x^4 - x^3 + 2x^2 - x) + 2C",
      "(x^4 - x^3 + 2x^2 - x) - C",
      "(x^4 - x^3 + 2x^2 - x) - 2C",
    ],
    correctIndex: 0,
  },
  {
    id: 38,
    theme: "Number Theory",
    difficulty: "hard",
    question:
      "What is the smallest positive integer that is divisible by all integers from 1 to 10?",
    options: ["2520", "360", "5040", "720"],
    correctIndex: 0,
  },
];
